name: Build onnxruntime, Upload Artifacts

on:
  # Run when the image builder changes
  push:
    branches:
      - master
  # Run daily at midnight to check for new versions
  schedule:
    - cron:  '0 0 * * *'

jobs:
  create-builder:
    runs-on: ubuntu-20.04
    steps:
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: pitop/onnxruntime-builder:latest
          file: Dockerfile.builder

  build:
    needs: create-builder
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.2.0

      - uses: docker/build-push-action@v2
        with:
          tags: ort-builder
          load: true

      - run: |
          docker create -ti --name ort-builder-tmp ort-builder bash
          docker cp ort-builder-tmp:/code/onnxruntime/build .

      - name: Upload build files
        uses: actions/upload-artifact@v2
        with:
          path: build
